config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/menu", to: "items#index"

  resources :items, only: [ :new, :create, :destroy ]

  get "/order/checkout", to: "checkout#show"

  get "owner", to: "owners#show"
  get "/owner/orders", to: "owners#orders"
  get "owner/menu", to: "owners#menu"
  get "owner/qr", to: "owners#qr"

  get "/tables/:table_id/dinners/new", to: "dinners#new", as: :new_dinner

  resources :orders, only: %i[create show update destroy] do
    get "/user_dashboard", to: "user_dashboards#show", as: :user_dashboard
  end
  resources :order_items, only: %i[create destroy create_menu]
  # resources :items
  resources :tables, only: [ :new, :create, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinner.rb
class Dinner < ApplicationRecord
  belongs_to :user
  belongs_to :table

  # has_many :orders, through: :users
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_one_attached :photo
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  has_many :order_items, dependent: :destroy
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_one_attached :photo
  has_many :items, through: :order_items
  belongs_to :user

  belongs_to :table
  # belongs_to :dinner, through: :users
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :dinners
  has_many :users, through: :dinners
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :order_items, through: :orders
  has_many :dinners
  has_many :tables, through: :dinners


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def show
    @items = current_user.order_items
  end
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  def new
    @dinner = Dinner.new
    @dinner.user = current_user
    @table = Table.find(params[:table_id])
    @dinner.table = @table
    @dinner.payment_status = false
    @dinner.save
    redirect_to root_path
  end

  private

  def table_params
    params.require(:table).permit(:table_number)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @user = current_user
    @order = @user.orders.find_by(status: "processing")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to owner_menu_path
    else
      render :new
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to request.referer
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :price, :photo)
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @user = current_user
    @item = Item.find(params[:item_id])
    if @user.orders.find_by(status: "processing").present?

      @order = @user.orders.find_by(status: "processing")
    else
      @order = Order.create(user: @user, table: $table)
    end
    OrderItem.create(order: @order, item: @item)

    unless @order.items.count > 1 && !request.referer.include?("orders")
      redirect_to request.referer
    end
  end

  def destroy
    @user = current_user
    @item = Item.find(params[:item_id])
    @order_item = OrderItem.find_by(item: @item)
    @order_item.destroy

    redirect_to request.referer
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if request.referer.include?("owner")
      @order.update(status: "ready to serve")
      redirect_to owner_orders_path(table: @order.table.id, anchor: "heading#{@order.table.id}")
    else
      @order.update(status: "complete")
      redirect_to order_user_dashboard_path(@order), notice: "Your order is being prepared"
    end
  end

  def destroy
    # @order = Order.find(params[:id])
    @user = current_user
    if @user.orders.find_by(status: "processing").present?
      @user.orders.find_by(status: "processing").destroy
      redirect_to menu_path, notice: "Your order has been deleted"
    end
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def show
    @orders = Order.all
    @dinners = Dinner.all
    @tables = Table.all
  end
  def menu
    @items = Item.all
    @item = Item.new
  end

  def orders
    @orders = Order.all
    @dinners = Dinner.all
    @tables = Table.all
  end


  def qr
    @tables = Table.all
    @new_table = Table.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home

  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def new
    @table = Table.new
  end

  def create
    @table = Table.new(table_params)
    @table.qr_code = "https://restrong-734.herokuapp.com/tables/#{@table.id}/dinners/new"
    if @table.save
      $table = @table
      redirect_to owner_qr_path(@table)
    else
      render :new
    end
  end

  def show
  @table = Table.find(params[:id])
  @qr_code = RQRCode::QRCode.new(@table.qr_code)
  @svg = @qr_code.as_svg(
    offset: 0,
    color: '000',
    shape_rendering: 'crispEdges',
    standalone: true
  )
  end


  private
  def table_params
    params.require(:table).permit(:table_number)
  end
end

app/controllers/user_dashboards_controller.rb
class UserDashboardsController < ApplicationController
  def show
    @user = current_user
    @order = Order.find(params[:order_id])
    @order2 = @user.orders
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkout/show.html.erb
<h1>Checkout</h1>
<% @items.each do |item| %>
  <p>
    <%= item.name %>
    <%= item.price %>
  </p>
<% end %>

app/views/dinner/new.html.erb
<h1>Welcome to our Restaurant</h1>

app/views/items/_accordion.html.erb
  <% i = 0 %>
  <% @items.each do |item| %>
    <div id="accordion">
      <div class="card bg-transparent">
        <div class="card-product d-flex justify-content-between text-center collapse panel-collapse" id="headingOne<%= i.to_s %>">
            <% if item.photo.attached? %>
              <%= cl_image_tag item.photo.key, height: 150, width: 150, crop: :fill, class: "m-0 p-2" %>
            <% else %>
              <img class ="m-0 p-2" src="https://media.istockphoto.com/photos/shakh-plov-picture-id1214641059?b=1&k=20&m=1214641059&s=170667a&w=0&h=O5nQMbhqaDaQFbM49RJpbTagWZMhaxo6C27-mgeRdbs="/>
            <% end %>
            <div id="name_content" class="m-1">
              <div>
                <%= item.name %>
              </div>
              <div>
                <button class="btn btn-link text-nowrap text-decoration-none" data-toggle="collapse" data-target="#collapseOne<%= i.to_s %>" aria-expanded="true" aria-controls="collapseOne<%= i.to_s %>">
                  See more
                </button>
              </div>
            </div>
            <div id="price_button" class="m-1">
            €<%= item.price %>
              <div class="button-bottom" data-toggle="modal" data-target="#FINAL">
                <%= link_to order_items_path(item_id: item), method: :post, id: "addTocart", class: "btn btn-primary", remote: true do %>
                <i class="fas fa-cart-plus" ></i>
                <% end %>
              </div>
          </div>
        </div>
        <div id="collapseOne<%= i.to_s %>" class="collapse hidden" aria-labelledby="headingOne<%= i.to_s %>" data-parent="#accordion">
          <div class="card-body">
            <h6>Description</h6>
            <%= item.description %>
          </div>
        </div>
      </div>
    </div>
    <% i+=1 %>
  <% end %>

app/views/items/_modal.html.erb
<div class="modal fade" id="FINAL" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="margin-top:40vw;">
  <div class="modal-dialog text-center" role="document">
    <div class="modal-content border-0 m-2" style="border-radius: 20px; margin: 0 !important;">
      <div class="modal-header border-0">
      </div>
      <div class="modal-body">
        <h4> Item </h4>
        <p class="text-muted">is added to Your Order!</p>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="button border-0" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<%# <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div> %>

app/views/items/index.html.erb
  <div class="cards">
  <div class="menu">
    <%= link_to(destroy_user_session_path, style: "color: #a26769;", method: :delete, id:"log-out-button") do %>
      <i class="fas fa-sign-out-alt fa-2x"></i>
    <% end %>
    <strong><h1>Menu</h1></strong>
  </div>

  <%= render partial: "accordion" %>

  <% if @order.present? %>
     <div class="d-flex justify-content-center stick-bottom">
      <%= link_to "My Order", order_path(@order), class: "button" %>
    </div>
  <% end %>
</div>
<%= render partial: "modal" %>

app/views/items/new.html.erb
<div class="forms">
  <h1>Create a new menu item</h1>
  <%= simple_form_for @item do |f| %>
    <%= f.input :name,required: true %>
    <%= f.input :description,required: true %>
    <%= f.input :price,required: true %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Restaurants of tomorrow | ReStrong </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta property="og:image" content="http://www.restrong.org/qr_code.jpg"/>
    <meta property="og:title" content="ReStrong"/>
    <meta property="og:description" content="Streamline food ordering process with ReStrong"/>
    <meta property="og:image:width" content="1200"/>
    <meta property="og:image:height" content="630"/>
    <meta property="og:url" content="http://www.restrong.org"/>
    <meta property="og:type" content="App"/>

  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<div style="min-height: 100vh; height: 100%; background: #e5e5e5;">

  <div class= "banner">
    <h1 class= "order-title">Your Orders</h1>
    <div class= "emoji">🥑</div>
  </div>

  <div class="cards p-4">
    <% @order.items.tally.each do |key,value| %>
    <div>
          <% item_name = key.name %>
          <% quantity = value %>
          <% price = key.price %>
          <div class="card-product d-flex justify-content-between">
            <% if key.photo.attached? %>
              <%= cl_image_tag key.photo.key, class: "m-0 p-2"%>
            <% else %>
              <img class ="m-0 p-2" src="https://media.istockphoto.com/photos/shakh-plov-picture-id1214641059?b=1&k=20&m=1214641059&s=170667a&w=0&h=O5nQMbhqaDaQFbM49RJpbTagWZMhaxo6C27-mgeRdbs="/>
            <% end %>
            <div class="container pl-2 pr-3">
              <div class="row">
                <div class="col-4">
                  <%= item_name %>
                </div>
                <div class="col-8 text-right">
                  <strong class="text-right">€<%= (price * quantity).round(2) %></strong>
                </div>
              </div>
              <div class="row pt-2">
                <div class="col-3">
                </div>
                <div class="col-9 text-right">
                  <div id="plus_minus">
                  <%= link_to order_item_path(item_id: key), method: :delete, class: "minus_button", remote: true do %>
                    <i id="minus-circle m-0", class="fas fa-minus-circle"></i>
                  <% end %>
                  <span class="spacing-quant"> (<%= quantity %>) </span>
                  <%= link_to order_items_path(item_id: key), class: "plus_button", method: :post do %>
                    <i id="plus-circle m-0", class="fa fa-plus-circle"></i>
                  <% end %>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="d-flex justify-content-between m-3">
        <p>Total:</p><%= "€#{(@order.items.sum(:price)).round(2)}" %>
      </div>
    </div>

  </div>
    <div class="d-flex justify-content-center text-nowrap text-center" style="right:13.6px; left:13.6px; bottom: 20px;">
      <%= link_to order_path(@order), method: :delete, class: "delete_button text-center m-2 1.5rem" do %>
      Delete order <i class="fas fa-trash mt-2 "></i>
      <% end %>
      <%= link_to "Send order 🔪", order_path(@order), method: :patch, class:"pay_button vw-50 text-center m-2" %>
    </div>
</div>

app/views/owners/_list.html.erb
<div id="accordion" style="font-size: large;">
  <% @tables.each do |table| %>
    <% if table.orders.count > 0 %>


      <div>
        <div class="card-header" id="heading<%= table.id %>">
          <h5 class="mb-0 d-flex justify-content-between">
            <button
              <% if table.id.to_s == params[:table] %>
                class="btn btn-link d-content"
              <% else %>
                class="btn btn-link collapsed d-content"
              <% end %>
              data-toggle="collapse"
              data-target="#collapse<%= table.id %>"
              aria-expanded="false"
              aria-controls="collapse<%= table.id %>"
              >
              <% if table.orders.map(&:status).uniq.length == 1 && table.orders.map(&:status).uniq[0] == "ready to serve" %>
                <p class="center-p-tag"> Table <%= table.table_number %> </p>
                <i class="fas fa-check-square" style="font-size: x-large;"></i>
              <% elsif table.orders.count == 0 %>
                Table <%= table.table_number %><br>
              <% else %>
                Table <%= table.table_number %><br>
                <% if table.orders.where(status: "complete").one? %>
                  <%= table.orders.where(status: "complete").count %> order pending
                <% else %>
                  <%= table.orders.where(status: "complete").count %> orders pending
                <% end %>
              <% end %>
            </button>

          </h5>

        </div>
        <div
          id="collapse<%= table.id %>"
          <% if table.id.to_s == params[:table] %>
            class="collapse open-card show"
          <% else %>
            class="collapse open-card"
          <% end %>
          aria-labelledby="heading<%= table.id %>"
          data-parent="#accordion"
        >

          <div
          <% if table.orders.where(status: "complete").count == 0 %>
            class="d-none"
          <% else %>
            class="card-body card-body-preparing"
          <% end %>
          >
            <% table.orders.where(status: "complete").each do |order| %>
              <b>
                <%= simple_form_for(order) do |f| %>
                  <div class="row ready-row" id="row" style="margin-top: 20px; margin-bottom: 5px;">
                    <p> Order <strong><%= order.id %></strong> <br>
                    <em style="font-size: smaller;">ordered <%= time_ago_in_words(order.created_at, include_seconds: true) %> ago</em>
                    </p>
                    <%= f.submit "Ready?", class: "button-submit-form", method: :patch, remote: true,
                    data: { disable_button_target: 'button',
                    action: 'click->disable-button#click'  } %>
                  </div>
                  <% order.items.tally.each do |item, count| %>
                    <div class="row" id="row">
                      <div class="col-8  border-bottom border-dark pl-0" style="margin-bottom: 10px;">-<%= item.name %></div>
                      <div class="col-2  border-bottom border-dark pl-0" style="margin-bottom: 10px;"><%= count %>x</div>
                      <div class="col-2  border-bottom border-dark pl-0" style="margin-bottom: 10px;">€<%= item.price %>  </div>
                    </div>
                  <% end %>
                  <div
                    class="row"
                    data-controller="disable-button"
                  >

                  </div>
                <% end %>
              </b>
            <% end %>
          </div>

          <div
          <% if table.orders.where(status: "ready to serve").count == 0 %>
            class="d-none"
          <% else %>
            class="card-body card-body-ready"
          <% end %>
          >

            <% table.orders.where(status: "ready to serve").each do |order| %>
              <s>
                <div class="row" id="row" style="margin-top: 20px; margin-bottom: 5px;">
                  Order <%= order.id %> is ready
                </div>
              </s>
                <% order.items.tally.each do |item, count| %>
                  <div class="row" id="row">
                    <div class="col-8 border-bottom border-dark pl-0" style="margin-bottom: 10px;">-<%= item.name %></div>
                    <div class="col-2 border-bottom border-dark pl-0" style="margin-bottom: 10px;"><%= count %>x</div>
                    <div class="col-2 border-bottom border-dark pl-0" style="margin-bottom: 10px;">€<%= item.price %>  </div>
                  </div>
                <% end %>
                <%# <div
                  class="row"
                  data-controller="disable-button"
                >
                </div> %>
            <% end %>
          </div>


          <div class="card-body">
            <div class="row" id="row">
              <div class="col-10 pl-0 border-bottom border-dark">
              Total:
              </div>
              <div class="col-2 pl-0 border-bottom border-dark total-sum">
                <% prices = table.orders.map(&:items).flatten.map(&:price) %>
                €<%= prices.sum %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<%# make a if statement depending on the order, if status is ready to serve then show in italic the order and disable button
else display the normal order with button %>

<%# .where(status: "complete" || "ready to serve") line 37%>

<%# if table.orders.status == "ready to serve"%>
<%# <% elsif table.orders.status == "complete"  %>
<%# end  %>

app/views/owners/_modal.html.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <% @tables.each do |table| %>
          <div class="row border-bottom border-dark" style="margin-top: 20px;"><h4>Table <%= table.table_number %></h4></div>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">Large modal</button>
          <% table.users.each do |user| %>
            <% user.orders.each do |order| %>
              <div class="row" style="margin-top: 20px; margin-bottom: 5px;"> Order <%= order.id %></div>
              <% order.items.tally.each do |item, count| %>
                <div class="row">
                  <div class="col-10 pl-0 border-bottom border-white" style="margin-bottom: 10px;">-<%= item.name %></div>
                  <div class="col-2 pl-0 border-bottom border-white" style="margin-bottom: 10px;"><%= count %>x</div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/owners/_modal_qr.html.erb
<div class="modal fade" id="QrBig" tabindex="-1" aria-labelledby="QrBigLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="QrBigLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/owners/menu.html.erb
<div class="background">
  <div class= "banner_owner">
    <h1 class= "order-title">MY MENU</h1>
    <div class= "emoji_owner">🥑</div>
  </div>
  <div class="d-flex flex-column align-items-between" style="height:65vh;">

  <div class="overflow-auto" style="margin-top: 50px; max-height:55vh" >
  <% i = 0 %>
    <% @items.each do |item| %>
      <div id="accordion">
        <div class="card bg-transparent">
          <div class="card-product d-flex justify-content-between text-center collapse panel-collapse" id="headingOne<%= i.to_s %>">
              <% if item.photo.attached? %>
                <%= cl_image_tag item.photo.key, height: 150, width: 150, crop: :fill, class: "m-0 p-2" %>
              <% else %>
                <img class ="m-0 p-2" src="https://media.istockphoto.com/photos/shakh-plov-picture-id1214641059?b=1&k=20&m=1214641059&s=170667a&w=0&h=O5nQMbhqaDaQFbM49RJpbTagWZMhaxo6C27-mgeRdbs="/>
              <% end %>
              <div id="name_content" class="m-1">
                <div>
                  <%= item.name %>
                </div>
                <div>
                  <button class="btn btn-link text-nowrap" data-toggle="collapse" data-target="#collapseOne<%= i.to_s %>" aria-expanded="true" aria-controls="collapseOne<%= i.to_s %>">
                    See more
                  </button>
                </div>
              </div>
              <div id="price_button" class="p-3">
              <%= item.price %>€
                <div class="button-bottom" data-toggle="modal" data-target="#FINAL">
                  <%= link_to item_path(item), method: :delete, remote: true do%>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </div>
            </div>
          </div>
          <div id="collapseOne<%= i.to_s %>" class="collapse hidden" aria-labelledby="headingOne<%= i.to_s %>" data-parent="#accordion">
            <div class="card-body" id="owner-menu-text-color">
              <h6>Description</h6>
              <%= item.description %>
            </div>
          </div>
        </div>
      </div>
      <% i+=1 %>
    <% end %>

  </div>
  <div class="d-flex justify-content-center flex-wrap" id="my-menu-buttons-owner" style="position:fixed; bottom: -15px; padding-bottom: 15px; background-color:#084C61">
    <button type="button" class="new-item-button vw-94 text-nowrap" style=" height:51px; width:330px; bottom: 20px; color:white; text-decoration:none; border-radius:30px; border: 0;" data-toggle="modal" data-target="#AddItem">
      NEW ITEM
    </button>
  <%= link_to "BACK", owner_path, class: "new-item-button m-1 vw-94 text-nowrap text-center", style:" color:white; width:330px; text-decoration:none; border-radius:30px; border: 0;" %>
  </div>
</div>
  <%= render partial: "modal_item" %>
</div>

app/views/owners/orders.html.erb
<div class="background">
  <div class= "banner_owner">
    <h1 class= "order-title">All Orders</h1>
    <div class= "emoji_owner">🥑</div>
  </div>

  <div class="container justify-content-center">
    <div style="margin-top: 50px;">
      <%= render partial: "list" %>
    </div>
  </div>
    <div class="d-flex justify-content-center stick-bottom">
      <%= link_to "Back", owner_path, class: "button" %>
    </div>
</div>

app/views/owners/qr.html.erb
<body style="background-color: #084C61">

<div class="mb-4" style="background-color: #084C61; height:100%; margin: 0px auto;">
  <div class= "banner_owner">
    <h1 class= "order-title">MY TABLES</h1>
    <div class= "emoji_owner">🥑</div>
  </div>
  <div class="d-flex flex-column align-items-between" style="height:65vh;">

  <div class="overflow-auto" style="margin-top: 50px; max-height:60vh" >
  <% i = 0 %>
    <% @tables.each do |table| %>
      <div id="accordion">
        <div class="card bg-transparent border-0">
          <div class="card-product d-flex justify-content-center collapse panel-collapse" id="headingOne<%= i.to_s %>">
                <button class="btn btn-link text-nowrap text-decoration-none" data-toggle="collapse" data-target="#collapseOne<%= i.to_s %>" aria-expanded="true" aria-controls="collapseOne<%= i.to_s %>">
                  <h6>Table: <%= table.table_number %></h6>
                </button>
          </div>
          <div id="collapseOne<%= i.to_s %>" class="collapse hidden card-product flex-wrap justify-content-center pb-2"  aria-labelledby="headingOne<%= i.to_s %>" data-parent="#accordion">
            <div class="d-flex card-body justify-content-center overflow-auto" id="owner-menu-text-color">
              <% table_id = table.id%>
              <% table.qr_code = "www.restrong.org/tables/#{table_id}/dinners/new" %>
              <% qr_code = RQRCode::QRCode.new(table.qr_code)%>
              <% svg = qr_code.as_svg( offset: 0, color: '000',module_size: 4, shape_rendering: 'crispEdges', standalone: true)%>
              <div>
                <%= svg.html_safe %>
              </div>
            </div>
            <!-- #Buttons
             <div class="text-center justify-content-between">
              <%= link_to "#restrong.org# ", "www.restrong.org/tables/#{table_id}/dinners/new" %>
              <%= link_to "#Local Host#", new_dinner_path(table) %>
            </div>
            -->
          </div>
        </div>
      </div>
      <% i+=1 %>
    <% end %>
  </div>

</div>
<div class="d-flex justify-content-between flex-wrap" style=" background-color: #084C61">
    <button type="button" class="button vw-100 m-1 text-nowrap" style=" box-shadow: 0px; color:white; text-decoration:none; border-radius:30px; border: 0;" data-toggle="modal" data-target="#AddTable">
      NEW TABLE
    </button>
    <%= link_to "BACK", owner_path, class: "button m-1 vw-100 text-nowrap text-center", style:"  box-shadow: 0px; color:white; text-decoration:none; border-radius:30px; border: 0;" %>
</div>
</div>
  <%= render partial: "modal_table" %>
  <%= render partial: "modal_qr" %>

</body>

app/views/pages/home.html.erb
<div class= "body" >
    <div class= "main-container">
    <div class="homepage-container">
      <% if current_user %>
      <h4 class= "homepage-title">Hello <%= current_user.first_name%>, <br>welcome to<br></h4>
      <%end %>
      <h1 class= "restaurant-name">"Tico-Taco"</h1>
      <h3 class = "restaurant-subtitle">🌮 Taquería 🌮</h3>
      <div class="d-flex justify-content-center">
          <%= link_to "Go To Menu", menu_path, class: "menu-button" %>
      </div>
    </div>
  </div>
  <div class= "footer">
    <p>Powered by ReStrong</p>
  </div>
</div>

app/views/tables/show.html.erb
<h1>Here is your QR-Code for table#<%= @table.table_number  %></h1>
<%= @svg.html_safe %>
<div>
<%= link_to "click", "https://restrong-734.herokuapp.com/tables/#{@table.table_number}/dinners/new" %>
<%= link_to "click", new_dinner_path(@table) %>
<%= link_to "Homepage", owner_path%>

</div>